import React, { useState } from 'react'
import { useSupabase } from '../hooks/useSupabase'
import { Gamepad2, Coins, Trophy, Zap, Star, Play, AlertCircle } from 'lucide-react'

interface LandingPageProps {
  onStartGame: () => void
}

export const LandingPage: React.FC<LandingPageProps> = ({ onStartGame }) => {
  const [isStarting, setIsStarting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const { signInAnonymously, isOfflineMode } = useSupabase()

  const handleStart = async () => {
    setIsStarting(true)
    setError(null)
    
    try {
      await signInAnonymously()
      onStartGame()
    } catch (error) {
      console.error('Error starting game:', error)
      setError('Failed to start game. Please try again.')
      setIsStarting(false)
    }
  }

  const features = [
    {
      icon: <Gamepad2 className="w-8 h-8" />,
      title: "Interactive Scenarios",
      description: "Face real-world financial challenges through engaging storylines"
    },
    {
      icon: <Zap className="w-8 h-8" />,
      title: "AI-Powered Outcomes",
      description: "Dynamic consequences generated by AI make every playthrough unique"
    },
    {
      icon: <Trophy className="w-8 h-8" />,
      title: "Earn Badges",
      description: "Unlock achievements as you master different financial skills"
    },
    {
      icon: <Star className="w-8 h-8" />,
      title: "Track Progress",
      description: "See your financial literacy improve with detailed progress tracking"
    }
  ]

  return (
    <div className="min-h-screen bg-black text-retro-teal overflow-hidden">
      <div className="crt-overlay"></div>
      
      <div className="relative z-10 max-w-6xl mx-auto px-4 py-8">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <div className="mb-8">
            <h1 className="text-4xl md:text-6xl font-bold mb-4 glitch">
              BUDGET<span className="text-retro-purple">HERO</span>
            </h1>
            <p className="text-xl md:text-2xl text-retro-purple mb-6">
              Your Financial Adventure Awaits
            </p>
            <div className="w-32 h-1 bg-gradient-to-r from-retro-teal to-retro-purple mx-auto mb-8"></div>
          </div>

          <div className="retro-panel p-8 rounded-lg mb-8 max-w-2xl mx-auto">
            <p className="text-lg mb-6 leading-relaxed">
              Welcome to the ultimate financial literacy game! Make choices, face consequences, 
              and learn money management through an epic choose-your-own-adventure experience.
            </p>
            
            <div className="flex items-center justify-center gap-4 mb-8">
              <div className="flex items-center gap-2 text-retro-teal">
                <Coins className="w-6 h-6" />
                <span>Start with $1,000</span>
              </div>
              <div className="w-2 h-2 bg-retro-purple rounded-full"></div>
              <div className="flex items-center gap-2 text-retro-purple">
                <Trophy className="w-6 h-6" />
                <span>Earn Badges</span>
              </div>
              <div className="w-2 h-2 bg-retro-teal rounded-full"></div>
              <div className="flex items-center gap-2 text-retro-teal">
                <Star className="w-6 h-6" />
                <span>AI-Powered Stories</span>
              </div>
            </div>

            {/* Offline Mode Notice */}
            {isOfflineMode && (
              <div className="bg-yellow-500/20 border border-yellow-500/50 rounded p-4 mb-6">
                <div className="flex items-center gap-2 text-yellow-400 mb-2">
                  <AlertCircle className="w-5 h-5" />
                  <span className="font-bold">Demo Mode</span>
                </div>
                <p className="text-sm text-yellow-200">
                  Running in offline mode. Progress won't be saved between sessions.
                </p>
              </div>
            )}

            {/* Error Message */}
            {error && (
              <div className="bg-red-500/20 border border-red-500/50 rounded p-4 mb-6">
                <div className="flex items-center gap-2 text-red-400">
                  <AlertCircle className="w-5 h-5" />
                  <span>{error}</span>
                </div>
              </div>
            )}

            <button
              onClick={handleStart}
              disabled={isStarting}
              className="pixel-button text-retro-teal border-retro-teal hover:bg-retro-teal hover:text-black px-8 py-4 text-lg disabled:opacity-50"
            >
              {isStarting ? (
                <div className="flex items-center gap-2">
                  <div className="animate-spin w-5 h-5 border-2 border-current border-t-transparent rounded-full"></div>
                  <span>Starting Adventure...</span>
                </div>
              ) : (
                <div className="flex items-center gap-2">
                  <Play className="w-5 h-5" />
                  <span>Start Adventure</span>
                </div>
              )}
            </button>
          </div>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {features.map((feature, index) => (
            <div key={index} className="retro-panel p-6 rounded-lg text-center">
              <div className="text-retro-purple mb-4 flex justify-center">
                {feature.icon}
              </div>
              <h3 className="text-lg font-bold mb-3">{feature.title}</h3>
              <p className="text-sm text-gray-300">{feature.description}</p>
            </div>
          ))}
        </div>

        {/* Sample Scenarios Preview */}
        <div className="retro-panel p-8 rounded-lg">
          <h2 className="text-2xl font-bold mb-6 text-center">
            Sample <span className="text-retro-purple">Scenarios</span>
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-black/50 p-4 rounded border border-retro-teal/30">
              <h3 className="font-bold text-retro-teal mb-2">💰 Rent Increase</h3>
              <p className="text-sm text-gray-300">
                Your landlord raised your rent by $300! Do you negotiate, move, or find a roommate?
              </p>
            </div>
            <div className="bg-black/50 p-4 rounded border border-retro-purple/30">
              <h3 className="font-bold text-retro-purple mb-2">🚗 Car Troubles</h3>
              <p className="text-sm text-gray-300">
                Your car needs $1,500 in repairs. Explore your options and face the consequences!
              </p>
            </div>
            <div className="bg-black/50 p-4 rounded border border-retro-teal/30">
              <h3 className="font-bold text-retro-teal mb-2">🏆 Job Promotion</h3>
              <p className="text-sm text-gray-300">
                A promotion offer requires relocation. Will you take the risk for higher pay?
              </p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center mt-16 text-sm text-gray-400">
          <p>© 2025 BudgetHero - Level up your financial literacy through gaming!</p>
        </div>
      </div>
    </div>
  )
}